In [2]:
import numpy as np

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [5]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.ones([2,3], dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.random.rand(3)

array([0.43256162, 0.94707495, 0.79363523])

In [15]:
np.random.rand(3,4)

array([[0.1484467 , 0.60318495, 0.93554484, 0.22140652],
       [0.4144978 , 0.83200946, 0.99057895, 0.72711006],
       [0.32933046, 0.92195668, 0.25100014, 0.1320805 ]])

In [21]:
np.random.randint(3)

2

In [22]:
np.random.randint(5,10)

6

In [24]:
np.random.randint(2,10,4)

array([3, 3, 7, 6], dtype=int32)

In [26]:
arr1 = np.random.randint(1,9,(4,5))
arr1

array([[8, 5, 2, 8, 1],
       [6, 5, 8, 6, 2],
       [7, 6, 3, 4, 3],
       [8, 3, 1, 3, 5]], dtype=int32)

In [27]:
arr1[0]

array([8, 5, 2, 8, 1], dtype=int32)

In [29]:
arr1[3]

array([8, 3, 1, 3, 5], dtype=int32)

In [30]:
arr1.shape

(4, 5)

In [31]:
arr1

array([[8, 5, 2, 8, 1],
       [6, 5, 8, 6, 2],
       [7, 6, 3, 4, 3],
       [8, 3, 1, 3, 5]], dtype=int32)

In [36]:
arr1[1,4]

np.int32(2)

In [37]:
print(arr1[1,4])

2


In [38]:
arr1[-3, 3]

np.int32(6)

In [39]:
arr1

array([[8, 5, 2, 8, 1],
       [6, 5, 8, 6, 2],
       [7, 6, 3, 4, 3],
       [8, 3, 1, 3, 5]], dtype=int32)

In [40]:
arr1[::-3]

array([[8, 3, 1, 3, 5],
       [8, 5, 2, 8, 1]], dtype=int32)

In [41]:
arr1[:4]

array([[8, 5, 2, 8, 1],
       [6, 5, 8, 6, 2],
       [7, 6, 3, 4, 3],
       [8, 3, 1, 3, 5]], dtype=int32)

In [42]:
arr1

array([[8, 5, 2, 8, 1],
       [6, 5, 8, 6, 2],
       [7, 6, 3, 4, 3],
       [8, 3, 1, 3, 5]], dtype=int32)

In [43]:
arr1[:40]

array([[8, 5, 2, 8, 1],
       [6, 5, 8, 6, 2],
       [7, 6, 3, 4, 3],
       [8, 3, 1, 3, 5]], dtype=int32)

In [46]:
arr1[:10]

array([[8, 5, 2, 8, 1],
       [6, 5, 8, 6, 2],
       [7, 6, 3, 4, 3],
       [8, 3, 1, 3, 5]], dtype=int32)

In [47]:
arr1[2:]

array([[7, 6, 3, 4, 3],
       [8, 3, 1, 3, 5]], dtype=int32)

In [48]:
arr1[10:]

array([], shape=(0, 5), dtype=int32)

In [49]:
arr1[:,0]

array([8, 6, 7, 8], dtype=int32)

In [50]:
arr1[:,4]

array([1, 2, 3, 5], dtype=int32)

In [51]:
arr1[:, -1]

array([1, 2, 3, 5], dtype=int32)

In [52]:
arr1[1:3, 1:3]

array([[5, 8],
       [6, 3]], dtype=int32)

In [53]:
arr1

array([[8, 5, 2, 8, 1],
       [6, 5, 8, 6, 2],
       [7, 6, 3, 4, 3],
       [8, 3, 1, 3, 5]], dtype=int32)

In [58]:
arr = [0,1,2,3,4,5]
arr

[0, 1, 2, 3, 4, 5]

In [66]:
arr.reshape(1,6)

AttributeError: 'list' object has no attribute 'reshape'

In [59]:
arr

[0, 1, 2, 3, 4, 5]