# NUMPY

In [1]:
import numpy as np 

In [3]:
np.__version__

'2.3.5'

In [6]:
import sys
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

In [7]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [8]:
type(my_list)

list

In [11]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [12]:
type(arr)

numpy.ndarray

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(10, 100, 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [17]:
np.arange(20, 10)

array([], dtype=int64)

In [19]:
np.arange(-20, 10) # 1st arg <2nd arg

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [24]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [25]:
np.zeros([2,2], dtype=int)

array([[0, 0],
       [0, 0]])

In [26]:
np.zeros([5,8], dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])